name: Approve and Merge MRI Team Count PR

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  approve-and-merge:
    runs-on: ubuntu-latest

    steps:
    - name: Approve PR (Only if Title Matches)
      if: github.event.pull_request.title == 'Auto PR: Update MRI Team Count'
      env:
        GH_TOKEN: ${{ secrets.BOT_PAT }}
        PR_URL: https://github.com/${{ github.repository }}/pull/${{ github.event.pull_request.number }}
      run: |
        echo "hahahha"
        gh pr review "$PR_URL" --approve

    - name: Merge PR (Only if Title Matches)
      if: github.event.pull_request.title == 'Auto PR: Update MRI Team Count'
      run: |
        echo "hahah2"
        gh pr merge "$PR_URL" --squash --delete-branch
      env:
        GH_TOKEN: ${{ secrets.BOT_PAT }}
        PR_URL: https://github.com/${{ github.repository }}/pull/${{ github.event.pull_request.number }}
